name: test_vulnerabilities
on: 
  push:
    branches:
      - main
jobs:
  openjdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Change Working Directory
        run: cd ./Java
      - name: Print in console
        run: ls
    
