name: test_vulnerabilities
on: 
  push:
    branches:
      - main
jobs:
  openjdk:
    env:
      image-name:  hello-grads
      output-file: open_jdk_vulnerabilities
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build container image
        run: | 
          cd ./Java/
          docker build -t ${{ env.image-name }} .
      - name: Run the container
        run: docker run ${{ env.image-name }}
      - name: Scan the image with Trivy
        run: docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $HOME/Library/Caches:/root/.cache/ aquasec/trivy image hello-grads > ${{ env.output-file }}
      - name: Output Vulnerabilities
        run: cat ${{ env.output-file }}
      
    
