name: test_vulnerabilities
on: 
  push:
    branches:
      - main
jobs:
  openjdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          working-directory: ./Java
      - name: Print in console
        run: ls
    
