name: test_vulnerabilities
on: 
  push:
    branches:
      - main
jobs:
  openjdk:
    env:
      image-name:  hello-grads
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build container image
        run: | 
          cd ./Java/
          docker build -t $image-name .
          docker image ls
          docker run $image-name
      
    
