name: test_vulnerabilities
on: 
 workflow_dispatch
  #push:
    #branches:
      #- main
jobs:

  openjdk-vulnerabilities:
    env:
      image-name:  hello-grads
      output-file: open_jdk_vulnerabilities
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Open JDK container image
        run: | 
          cd ./Java/
          docker build -t ${{ env.image-name }} .
      - name: Run the container
        run: docker run ${{ env.image-name }}
      - name: Scan the image with Trivy
        run: docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $HOME/Library/Caches:/root/.cache/ aquasec/trivy image hello-grads > ${{ env.output-file }}
      - name: Output Vulnerabilities
        run: cat ${{ env.output-file }}
        
  wolfi-jre-vulnerabilites:
    env:
      image-name: hello-grads-wolfi:one
      output-file: wolfi-jre-vulnerabilities
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Build Wolfi JRE image
        run: |
          cd ./Wolfi-JRE/
          docker build -t  ${{ env.image-name }} .
      - name: Scan the image with Trivy
        run: docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $HOME/Library/Caches:/root/.cache/ aquasec/trivy image ${{ env.image-name }} > ${{ env.output-file }}
      - name: Output Vulnerabilities
        run: cat ${{ env.output-file}}
          
      
    
